version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:19-jdk
        auth:
          username: DOCKER_HUB_LOGIN
          password: DOCKER HUB_PASS
    steps:
      - checkout
      - run: mvn clean package
      - run: mvn test

workflows:
  - build:
    context:
     -build-env-vars
     -docker-hub-creds
    version: 2
    build_and_test:
    jobs:
      - build