CREATE TABLE PESSOA(
ID_PES INT NOT NULL AUTO_INCREMENT,
NOM_PES VARCHAR NOT NULL,
DAT_NAS TIMESTAMP NOT NULL,
VER_PES INT NOT NULL DEFAULT 1,
CRE_AT_PES TIMESTAMP NOT NULL,
UPD_AT_PES TIMESTAMP NOT NULL,
PRIMARY KEY(ID_PES)
);

CREATE TABLE ENDERECO(
ID_END INT NOT NULL AUTO_INCREMENT,
ID_PES INT NOT NULL,
LOG_END VARCHAR NOT NULL,
NUM_END INT NOT NULL,
CEP_END VARCHAR NOT NULL,
PRI_END BOOLEAN NOT NULL,
CID_END VARCHAR NOT NULL,
VER_END INT NOT NULL DEFAULT 1,
CRE_AT_END TIMESTAMP NOT NULL,
UPD_AT_END TIMESTAMP NOT NULL,
PRIMARY KEY(ID_END),
FOREIGN KEY (ID_PES) REFERENCES PESSOA(ID_PES)
);


