CREATE TABLE IF NOT EXISTS endereco(
id_end BIGINT(20) NOT NULL AUTO_INCREMENT,
log_end VARCHAR(255) NOT NULL,
num_end INT(30) NOT NULL,
cid_end VARCHAR(255) NOT NULL,
CONSTRAINT pk_id_end PRIMARY KEY(id_end),
CONSTRAINT fk_end_pes FOREIGN KEY (id_pes) REFERENCES pessoa(id_pes)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS pessoa(
id_pes BIGINT(20) NOT NULL AUTO_INCREMENT,
nom_pes VARCHAR(255) NOT NULL,
dat_nas VARCHAR(255) NOT NULL,
id_end BIGINT(20) NOT NULL AUTO_INCREMENT,
ver_pes INT(11) NOT NULL DEFAULT 1;
cre_at_pes DATE TIME NOT NULL DEFAULT CURRENT_STAMP,
upd_at_pes DATE TIME NOT NULL DEFAULT CURRENT_STAMP,
CONSTRAINT pk_id_pes PRIMARY KEY(id_pes),
CONSTRAINT fk_pes_end FOREIGN KEY (id_end) REFERENCES endereco(id_end)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;